version: '2.3'

services:
  sqs:
    container_name: sqs
    image: roribio16/alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./local-sqs.conf:/opt/config/elasticmq.conf
